KanbanBoardDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('kanban.urls')),
    path('admin/', admin.site.urls),
]

kanban/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

task_crud_patterns = [
    path('task/<uuid:pk>', views.TaskDetailView.as_view(), name='task-detail'),
    path('task/add', views.TaskCreate.as_view(), name='task-add'),
    path('task/edit/<uuid:pk>', views.TaskUpdate.as_view(), name='task-edit'),
    path('task/delete/<uuid:pk>', views.TaskDelete.as_view(), name='task-delete'),
]
urlpatterns += task_crud_patterns

task_action_patterns = [
    path('task/actions/increase_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'increase_priority'},
         name='task-action-increase_priority'),
    path('task/actions/decrease_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'decrease_priority'},
         name='task-action-decrease_priority'),
    path('task/actions/increase_status/<uuid:pk>', views.TaskAction.as_view(), {'action': 'increase_status'},
         name='task-action-increase_status'),
    path('task/actions/decrease_status/<uuid:pk>', views.TaskAction.as_view(), {'action': 'decrease_status'},
         name='task-action-decrease_status'),
    path('task/actions/max_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'max_priority'},
         name='task-action-max_priority'),
    path('task/actions/min_priority/<uuid:pk>', views.TaskAction.as_view(), {'action': 'min_priority'},
         name='task-action-min_priority'),
]
urlpatterns += task_action_patterns

task_comment_crud_patterns = [
    path('task_comment/add/', views.TaskCommentCreate.as_view(), name='taskcomment-add'),
    path('task_comment/add/<uuid:task_pk>', views.TaskCommentCreate.as_view(), name='taskcomment-add-specific'),
    path('task_comment/edit/<uuid:pk>', views.TaskCommentUpdate.as_view(), name='taskcomment-edit-specific'),
    path('task_comment/delete/<uuid:pk>', views.TaskCommentDelete.as_view(), name='taskcomment-delete'),
]
urlpatterns += task_comment_crud_patterns

account_views = [
    path('accounts/tasks/', views.UserTasks.as_view(), name='user-tasks'),
    path('accounts/login/', views.KanbanLogin.as_view(), name='accounts-login'),
    path('accounts/logout/', views.KanbanLogout.as_view(), name='accounts-logout'),
]
urlpatterns += account_views

kanban/models/task.py
import datetime
import uuid

from django.urls import reverse
from django.db import models


class Task(models.Model):
    class Meta:
        ordering = ['-date_modified']

    STATUS_CHOICES = {
        ('TODO', 'To Do'),
        ('PROG', 'In Progress'),
        ('TEST', 'In Testing'),
        ('DONE', 'Done'),
    }

    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    priority = models.IntegerField(default=0)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default='TODO')

    date_created = models.DateTimeField(default=datetime.datetime.now())
    date_modified = models.DateTimeField(default=datetime.datetime.now())
    author = models.CharField(max_length=200, default='No Author')

    def __str__(self):
        return '{title}'.format(title=self.title)

    def get_absolute_url(self):
        return reverse('task-detail', kwargs={'pk': self.uuid})

    def increase_status(self) -> None:
        if self.status == 'TODO':
            self.status = 'PROG'
        elif self.status == 'PROG':
            self.status = 'TEST'
        elif self.status == 'TEST':
            self.status = 'DONE'

        self.save()

    def decrease_status(self) -> None:
        if self.status == 'PROG':
            self.status = 'TODO'
        elif self.status == 'TEST':
            self.status = 'PROG'
        elif self.status == 'DONE':
            self.status = 'TEST'

        self.save()

    def max_priority(self) -> None:
        cur_max_priority = Task.objects.all().aggregate(models.Max('priority'))['priority__max']

        self.priority = cur_max_priority + 1
        self.save()

    def min_priority(self) -> None:

        cur_min_priority = Task.objects.all().aggregate(models.Min('priority'))['priority__min']

        self.priority = cur_min_priority - 1
        self.save()

kanban/models/task_comment.py
from django.db import models

import datetime
import uuid

from .import Task


class TaskComment(models.Model):
    class Meta:
        ordering = ['-date_created']

    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4())

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    text = models.TextField()

    date_created = models.DateTimeField(default=datetime.datetime.now())
    date_modified = models.DateTimeField(default=datetime.datetime.now())
    author = models.CharField(max_length=200, default='No Author')

    def __str__(self):
        return '{author} - {task}:{text}...'.format(author=self.author, task=self.task.title, text=self.text[:25])

kanban/views/index.py
from django.views.generic import  TemplateView

from ..models import Task

class Index(TemplateView):
    template_name = 'kanban/index.html'


    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)

        context['TODO_list'] = Task.objects.filter(status='TODO').order_by('-priority')[:15]
        context['PROG_list'] = Task.objects.filter(status='PROG').order_by('-priority')[:15]
        context['TEST_list'] = Task.objects.filter(status='TEST').order_by('-priority')[:15]
        context['DONE_list'] = Task.objects.filter(status='DONE').order_by('-priority')[:15]

        return context

kanban/views/kanbanLogin.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

class KanbanLogin(auth_views.LoginView):
    template_name = 'registration/login.html'
    extra_context = {'next': reverse_lazy('index')}

kanban/views/kanbanLogout.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

class KanbanLogout(auth_views.LogoutView):
    next_page = reverse_lazy('index')
    template_name = 'registration/logout.html'

kanban/views/taskActions.py
from django.urls import reverse
from django.shortcuts import  get_object_or_404
from django.views.generic import RedirectView


from ..models import Task

class TaskAction(RedirectView):

    def get_redirect_url(self, *args, **kwargs):

        action = kwargs.get('action')
        task_pk = kwargs.get('pk')

        task = get_object_or_404(Task, pk=task_pk)

        if action == 'increase_priority':
            task.priority += 1

        elif action == 'decrease_priority':
            task.priority -= 1

        elif action == 'increase_status':
            task.increase_status()

        elif action == 'decrease_status':
            task.decrease_status()

        elif action == 'max_priority':
            task.max_priority()

        elif action == 'min_priority':
            task.min_priority()
        task.save()
        return reverse('index')

kanban/views/taskCommentForms.py
import datetime

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from kanban.models import TaskComment


class TaskCommentCreate(CreateView):
    model = TaskComment
    fields = '__all__'
    template_name = 'kanban/taskcomment_create_form.html'

    def get_initial(self):

        initial = {'task': self.kwargs.get('task_pk')}

        if self.request.user.is_authenticated:
            initial.update({'author': self.request.user.username})

        return initial

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})


class TaskCommentUpdate(UpdateView):
    model = TaskComment
    fields = '__all__'
    template_name = 'kanban/taskcomment_edit_form.html'

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})


class TaskCommentDelete(DeleteView):
    model = TaskComment

    def get_success_url(self):
        return reverse_lazy('task-detail', kwargs={'pk':self.object.task.uuid})

kanban/views/taskDetailView.py
from django.views.generic import DetailView

from ..models import Task


class TaskDetailView(DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'kanban/task_detail.html'

kanban/views/taskForms.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from kanban.models import Task


class TaskCreate(CreateView):
    model = Task
    fields = '__all__'
    template_name = 'kanban/task_create_form.html'
    success_url = reverse_lazy('index')

    def get_initial(self):
        inital = {}

        if self.request.user.is_authenticated:
            inital.update( {'author': self.request.user.username} )

        return inital

class TaskUpdate(UpdateView):
    model = Task
    fields = '__all__'
    template_name = 'kanban/task_edit_form.html'
    success_url = reverse_lazy('index')


class TaskDelete(DeleteView):
    model = Task
    success_url = reverse_lazy('index')

kanban/views/userTasks.py
from . import Index

from ..models import Task


class UserTasks(Index):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        todo_tasks = Task.objects.filter(status='TODO', author=self.request.user.username)
        prog_tasks = Task.objects.filter(status='PROG', author=self.request.user.username)
        test_tasks = Task.objects.filter(status='TEST', author=self.request.user.username)
        done_tasks = Task.objects.filter(status='DONE', author=self.request.user.username)

        context['TODO_list'] = todo_tasks.order_by('-priority')[:15]
        context['PROG_list'] = prog_tasks.order_by('-priority')[:15]
        context['TEST_list'] = test_tasks.order_by('-priority')[:15]
        context['DONE_list'] = done_tasks.order_by('-priority')[:15]

        return context


kanban/templates/kanban/index.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Kanban Board {% endblock %}

{% block content %}
<div class="container-fluid py-5">
    <div class="row mb-4">
        <h1 class="text-primary">Django Kanban Board</h1>
        <div>
            {% if user.is_authenticated %}
                <strong>{{ user.username|capfirst }}</strong>
                <a href="{% url 'accounts-logout'%}" class="btn btn-sm btn-danger">Logout</a>
                <a href="{% url 'index' %}" class="btn btn-sm btn-secondary">All Tasks</a>
                <a href="{% url 'user-tasks' %}" class="btn btn-sm btn-info">My Tasks</a>
                <a href="{% url 'task-add' %}" class="btn btn-sm btn-success">Add Task</a>
            {% else %}
                <a href="{% url 'accounts-login' %}" class="btn btn-sm btn-primary">Login</a>
            {% endif %}
        </div>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
        {% include 'kanban/index_task_list.html' with task_list=TODO_list title='Tasks To Do'%}
        {% include 'kanban/index_task_list.html' with task_list=PROG_list title='Tasks In Progress' %}
        {% include 'kanban/index_task_list.html' with task_list=TEST_list title='Tasks In Testing' %}
        {% include 'kanban/index_task_list.html' with task_list=DONE_list title='Tasks Finished' %}
    </div>
</div>
{% endblock %}

kanban/templates/kanban/index_task_list.html
<div id="{{ title|slugify }}" class="kanban-tasklist col">
    <div class="p-3 bg-light rounded shadow-sm">
        <h4 class="text-center text-primary">{{ title }}</h4>
        <hr>
        <div class="task-container">
            {% if task_list %}
                {% for task in task_list %}
                    <div id="task-{{ task.id }}" class="kanban-tasklist-taskpanel" data-id="{{ task.id }}">
                        {% include 'kanban/index_task_panel.html' with task=task %}
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-muted text-center">No Tasks Present</p>
            {% endif %}
        </div>
    </div>
</div>

kanban/templates/kanban/index_task_panel.html
<div class="kanban-tasklist-taskpanel p-3 mb-3 bg-white rounded shadow-sm">
    <h6 class="fw-bold">
        <a href="{% url 'task-detail' pk=task.uuid %}" class="text-dark text-decoration-none">
            {{ task.title|slice:":45" }}
        </a>
    </h6>
    <p class="text-muted mb-2">
        <small>{{ task.date_created }} | {{ task.author }}</small> <br>
        <small>
            {% if task.description %}
                {{ task.description|slice:":120" }}
                {% if task.description|length > 120 %} ... {% endif %}
            {% else %}
                - ...
            {% endif %}
        </small>
    </p>
    <small>
        <a href="{% url 'task-action-decrease_status' pk=task.uuid %}" class="btn btn-sm btn-outline-secondary">⬅</a>
        <a href="{% url 'task-action-increase_status' pk=task.uuid %}" class="btn btn-sm btn-outline-secondary">➡</a>
        <a href="{% url 'task-action-max_priority' pk=task.uuid%}" class="btn btn-sm btn-success">Top</a>
        <a href="{% url 'task-action-min_priority' pk=task.uuid%}" class="btn btn-sm btn-danger">Bottom</a>
        <a href="{% url 'task-action-increase_priority' pk=task.uuid %}" class="btn btn-sm btn-warning">+</a>
        <a href="{% url 'task-action-decrease_priority' pk=task.uuid %}" class="btn btn-sm btn-warning">-</a>
        <a href="{% url 'task-edit' pk=task.uuid %}" class="btn btn-sm btn-primary">Edit</a>
    </small>
    <hr>
</div>

kanban/templates/kanban/kanban_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %} Kanban Board {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'kanban/kanban.css' %}">
</head>
<body class="bg-light">
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/Sortable.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const columns = document.querySelectorAll(".kanban-tasklist");
            columns.forEach((column) => {
                Sortable.create(column, {
                    group: "shared",
                    animation: 150,
                    onEnd: function (evt) {
                        const taskId = evt.item.getAttribute("data-id");
                        const newStatus = evt.to.id;
                        
                        fetch(`/update-task-status/${taskId}/`, {
                            method: "POST",
                            headers: {
                                "Content-Type": "application/json",
                                "X-CSRFToken": "{{ csrf_token }}",
                            },
                            body: JSON.stringify({ status: newStatus }),
                        }).then(response => response.json())
                          .then(data => console.log(data));
                    },
                });
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/Sortable.min.js"></script>
    <script>
    document.addEventListener("DOMContentLoaded", () => {
        const columns = document.querySelectorAll(".task-container");
    
        columns.forEach((column) => {
            Sortable.create(column, {
                group: "tasks",
                animation: 150,
                draggable: ".kanban-tasklist-taskpanel",
                onEnd: function (evt) {
                    const taskId = evt.item.getAttribute("data-id");
                    const newStatus = evt.to.closest(".kanban-tasklist").id;
    
                    fetch(`/update-task-status/${taskId}/`, {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json",
                            "X-CSRFToken": "{{ csrf_token }}",
                        },
                        body: JSON.stringify({ status: newStatus }),
                    }).then(response => response.json())
                      .then(data => console.log(data));
                },
            });
        });
    });
    </script>
    
</body>
</html>

kanban/templates/kanban/task_create_form.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Add Task {% endblock %}

{% block content %}
<div class="card p-4 mt-5 shadow-sm">
    <h2 class="text-center text-primary mb-4">Add Task</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-success w-100">Save Task</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/task_detail.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Task: {{ task.title }} {% endblock %}

{% block content %}
<div class="card p-4 mt-5 shadow-sm">
    <h2 class="text-center text-primary">Task: {{ task.title }}</h2>

    <p><strong>Status:</strong> {{ task.get_status_display }}</p>

    <div class="mb-3">
        <a href="{% url 'task-edit' task.uuid %}" class="btn btn-primary btn-sm">Edit</a>
        <a href="{% url 'index' %}" class="btn btn-secondary btn-sm">Back To Board</a>
    </div>

    <hr>

    <p>
        <strong>Description:</strong><br>
        {{ task.description }}
    </p>

    <p>
        <strong>Comments:</strong><br>
        <a href="{% url 'taskcomment-add-specific' task_pk=task.uuid %}" class="btn btn-outline-success btn-sm">Add Comment</a>
    </p>

    {% if task.taskcomment_set.all %}
        <ul class="list-group mt-3">
            {% for task_comment in task.taskcomment_set.all %}
                <li class="list-group-item">
                    <p>{{ task_comment.text }}</p>
                    <small class="text-muted">{{ task_comment.author }} - {{ task_comment.date_created }}</small>
                    <a href="{% url 'taskcomment-edit-specific' pk=task_comment.pk %}" class="btn btn-sm btn-link">Edit</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <hr>

    <p>
        <strong>Author:</strong> {{ task.author }} <br>
        <strong>Date Created:</strong> {{ task.date_created }} <br>
        <strong>Last Modified:</strong> {{ task.date_modified }}
    </p>
</div>
{% endblock %}

kanban/templates/kanban/task_edit_form.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Edit Task {% endblock %}

{% block content %}
<div class="card p-4 mt-5 shadow-sm">
    <h2 class="text-center text-primary mb-4">Edit Task</h2>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="submit" class="btn btn-danger" formaction="{% url 'task-delete' pk=task.pk %}">Delete</button>
        </div>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/taskcomment_create_form.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Add Comment {% endblock %}

{% block content %}
<div class="card p-4 mt-5 shadow-sm">
    <h2 class="text-center text-primary mb-4">Add Comment</h2>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <button type="submit" class="btn btn-success w-100">Save</button>
    </form>
</div>
{% endblock %}

kanban/templates/kanban/taskcomment_edit_form.html
{% extends 'kanban/kanban_base.html' %}

{% block title %} Edit Comment {% endblock %}

{% block content %}
<div class="card p-4 mt-5 shadow-sm">
    <h2 class="text-center text-primary mb-4">Edit Comment</h2>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="submit" class="btn btn-danger" formaction="{% url 'taskcomment-delete' pk=taskcomment.pk %}">Delete</button>
        </div>
    </form>
</div>
{% endblock %}